#!/usr/bin/env bash
set -euo pipefail

# PreToolUse(Write|Edit|MultiEdit) — blocks writes to lock files, .env, vendor dirs.
# Warns for generated files, CI configs, git hooks.

INPUT=$(cat)

FILE_PATH=$(jq -r '.tool_input.file_path // empty' <<< "$INPUT" 2>/dev/null || echo "")

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

BASENAME=$(basename "$FILE_PATH")
LOWER_PATH=$(echo "$FILE_PATH" | tr '[:upper:]' '[:lower:]')

# --- BLOCK patterns (exit 2) ---

# Lock files — these are generated by package managers
case "$BASENAME" in
  package-lock.json|yarn.lock|pnpm-lock.yaml|composer.lock|Gemfile.lock|poetry.lock|Pipfile.lock|go.sum|Cargo.lock|flake.lock)
    echo '{"hookSpecificOutput":{"decision":"block","reason":"Blocked: '"$BASENAME"' is a lock file generated by a package manager. Run the appropriate install/update command instead of editing it directly."}}'
    exit 2
    ;;
esac

# .env files (but not .env.example, .env.sample, .env.template)
if [[ "$BASENAME" == ".env" ]] || echo "$BASENAME" | grep -qP '^\.env\.(local|development|production|staging|test)$'; then
  echo '{"hookSpecificOutput":{"decision":"block","reason":"Blocked: '"$BASENAME"' contains environment-specific secrets. Edit .env.example instead and document the required variables."}}'
  exit 2
fi

# Vendor/dependency directories
if [[ "$LOWER_PATH" == *"/node_modules/"* ]] || \
   [[ "$LOWER_PATH" == *"/vendor/"* ]] || \
   [[ "$LOWER_PATH" == *"/__pycache__/"* ]] || \
   [[ "$LOWER_PATH" == *"/.venv/"* ]] || \
   [[ "$LOWER_PATH" == *"/venv/"* ]] || \
   [[ "$LOWER_PATH" == *"/.tox/"* ]] || \
   [[ "$LOWER_PATH" == *"/dist/"* && "$LOWER_PATH" != *"/src/dist/"* ]] || \
   [[ "$LOWER_PATH" == *"/build/lib/"* ]] || \
   [[ "$LOWER_PATH" == *"/.eggs/"* ]]; then
  echo '{"hookSpecificOutput":{"decision":"block","reason":"Blocked: this file is inside a generated/vendor directory ('"$(dirname "$FILE_PATH")"'). These directories should not be manually edited."}}'
  exit 2
fi

# --- WARN patterns (additionalContext, exit 0) ---

# Generated files
if [[ "$BASENAME" == *".generated."* ]] || \
   [[ "$BASENAME" == *".gen."* ]] || \
   [[ "$BASENAME" == *"_generated."* ]] || \
   [[ "$BASENAME" == *"_gen."* ]] || \
   [[ "$BASENAME" == *".min.js" ]] || \
   [[ "$BASENAME" == *".min.css" ]] || \
   [[ "$BASENAME" == *".d.ts" && "$BASENAME" != *".test.d.ts" ]]; then
  echo '{"hookSpecificOutput":{"additionalContext":"Warning: '"$BASENAME"' appears to be a generated file. Edits may be overwritten by the generator. Consider modifying the source instead."}}'
  exit 0
fi

# CI/CD config files
if [[ "$LOWER_PATH" == *"/.github/workflows/"* ]] || \
   [[ "$BASENAME" == ".gitlab-ci.yml" ]] || \
   [[ "$BASENAME" == "Jenkinsfile" ]] || \
   [[ "$BASENAME" == ".circleci/config.yml" ]] || \
   [[ "$LOWER_PATH" == *"/.buildkite/"* ]]; then
  echo '{"hookSpecificOutput":{"additionalContext":"Warning: modifying CI/CD configuration. Changes here affect the build pipeline for all contributors. Test carefully."}}'
  exit 0
fi

# Git hooks directory
if [[ "$LOWER_PATH" == *"/.git/hooks/"* ]] || [[ "$LOWER_PATH" == *"/.husky/"* ]]; then
  echo '{"hookSpecificOutput":{"additionalContext":"Warning: modifying git hooks. These affect every contributor'\''s local workflow."}}'
  exit 0
fi

exit 0
